---
name: chat_app_version_one
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  modal_progress_hud_nsn: ^0.4.0
  cloud_firestore: ^4.8.2
  flutter_bloc: ^8.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: Pacifico
    fonts:
    - asset: assets/fonts/Pacifico-Regular.ttf
flutter_launcher_icons:
  image_path: "iconApp/talkup.png"
  android: true
  ios: true