// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ7XiHvjKg8zA3ecaMdlsJxK73vgU4yJE',
    appId: '1:984840468565:web:a6f799ace598dbf7f8fcdc',
    messagingSenderId: '984840468565',
    projectId: 'chat-app-f8e1a',
    authDomain: 'chat-app-f8e1a.firebaseapp.com',
    storageBucket: 'chat-app-f8e1a.appspot.com',
    measurementId: 'G-CEG8MMB3GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-IEYcbdMaJkem62ItwZGcQu_4YpVeoGU',
    appId: '1:984840468565:android:6fe1cc06be3eb3def8fcdc',
    messagingSenderId: '984840468565',
    projectId: 'chat-app-f8e1a',
    storageBucket: 'chat-app-f8e1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWhHgR23Ef0mXfpR8QSj8HmMmOxYEYO6U',
    appId: '1:984840468565:ios:c6dbcd59e8088396f8fcdc',
    messagingSenderId: '984840468565',
    projectId: 'chat-app-f8e1a',
    storageBucket: 'chat-app-f8e1a.appspot.com',
    iosClientId: '984840468565-5l5otgiick0jrar370a4nnqlutcnopnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppVersionOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWhHgR23Ef0mXfpR8QSj8HmMmOxYEYO6U',
    appId: '1:984840468565:ios:c6dbcd59e8088396f8fcdc',
    messagingSenderId: '984840468565',
    projectId: 'chat-app-f8e1a',
    storageBucket: 'chat-app-f8e1a.appspot.com',
    iosClientId: '984840468565-5l5otgiick0jrar370a4nnqlutcnopnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppVersionOne',
  );
}
